import './globals.css';
import type { Metadata } from 'next';
import { Roboto } from 'next/font/google';
import 'rc-slider/assets/index.css';
import 'swiper/css';
import 'swiper/css/pagination';
import 'swiper/css/navigation';
import { Providers } from '@/redux/provider';
import { ToastContainer } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';
import ReactQueryProvider from '@/providers/RQProvider';

const font = Roboto({
    subsets: ['latin'],
    weight: ['400', '500', '700'],
    style: ['italic', 'normal'],
});

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
    return (
        <html lang="en">
            <body className={font.className}>
                <ReactQueryProvider>
                    <ToastContainer />
                    <Providers>{children}</Providers>
                </ReactQueryProvider>
            </body>
        </html>
    );
}
